<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::connection()->getDriverName() !== 'sqlite') {
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        }

        Product::truncate();

        if (DB::connection()->getDriverName() !== 'sqlite') {
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        }

        // Image pools — local paths relative to public/
        $img = [
            'mod'     => ['images/products/mod/mod-1.jpg','images/products/mod/mod-2.jpg','images/products/mod/mod-3.jpg','images/products/mod/mod-4.jpg','images/products/mod/mod-5.jpg','images/products/mod/mod-6.jpg'],
            'pod'     => ['images/products/pod/pod-1.jpg','images/products/pod/pod-2.jpg','images/products/pod/pod-3.jpg','images/products/pod/pod-4.jpg','images/products/pod/pod-5.jpg'],
            'liquid'  => ['images/products/liquid/liq-1.jpg','images/products/liquid/liq-2.jpg','images/products/liquid/liq-3.jpg','images/products/liquid/liq-4.jpg','images/products/liquid/liq-5.jpg','images/products/liquid/liq-6.jpg'],
            'coil'    => ['images/products/coil/coil-1.jpg','images/products/coil/coil-2.jpg','images/products/coil/coil-3.jpg'],
            'starter' => ['images/products/starter/starter-1.jpg','images/products/starter/starter-2.jpg','images/products/starter/starter-3.jpg'],
            'battery' => ['images/products/battery/bat-1.jpg','images/products/battery/bat-2.jpg'],
        ];

        $products = $this->products();

        $counts = [];
        foreach ($products as $data) {
            $cat = $data['category'];
            $counts[$cat] = $counts[$cat] ?? 0;
            $pool = $img[$cat] ?? $img['mod'];
            $image = $pool[$counts[$cat] % count($pool)];
            $counts[$cat]++;

            Product::create([
                ...$data,
                'slug'  => Str::slug($data['name']),
                'image' => $image,
            ]);
        }
    }

    /** @return array<int,array<string,mixed>> */
    private function products(): array
    {
        return [
            // ════════════════════════════════════════
            // MOD BOX (15 produk)
            // ════════════════════════════════════════
            ['name'=>'VOOPOO DRAG 4 177W','brand'=>'VOOPOO','category'=>'mod','description'=>'Chipset GENE.FAN 2.0 dengan layar TFT 0.96" berwarna. Dual 18650, output 5–177W dengan mode SMART/RTA/TC. Desain ergonomis dengan grip side panel.','specs'=>'Chipset: GENE.FAN 2.0|Baterai: 2×18650|Output: 5-177W|Layar: 0.96" TFT|Ukuran: 94×55×30mm','price'=>749000,'price_original'=>950000,'badge'=>'hot','color_gradient'=>'grad-purple','stock'=>15,'rating'=>4.9,'review_count'=>248],
            ['name'=>'GeekVape Aegis X 200W','brand'=>'GEEKVAPE','category'=>'mod','description'=>'Waterproof IP67, shockproof & dustproof untuk pemakaian outdoor. Chipset AS Chip 2.0 dan layar 0.96" TFT. Salah satu mod paling tahan lama di pasaran.','specs'=>'Chipset: AS Chip 2.0|Baterai: 2×18650|Output: 5-200W|Waterproof: IP67|Layar: 0.96" TFT','price'=>1250000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-red','stock'=>8,'rating'=>5.0,'review_count'=>427],
            ['name'=>'Lost Vape Thelema Quest 200W','brand'=>'LOST VAPE','category'=>'mod','description'=>'Chipset Quest terbaru dengan dual 18650 dan layar 0.96" IPS TFT penuh warna. Bodi zinc alloy + kulit sintetis premium dengan rasa di tangan yang mewah.','specs'=>'Chipset: Quest|Baterai: 2×18650|Output: 5-200W|Layar: 0.96" IPS TFT|Material: Zinc Alloy + Leather','price'=>875000,'price_original'=>1100000,'badge'=>'hot','color_gradient'=>'grad-indigo','stock'=>12,'rating'=>4.9,'review_count'=>389],
            ['name'=>'SMOK MAG P3 230W','brand'=>'SMOK','category'=>'mod','description'=>'Mod berbentuk pistol ikonik dari SMOK dengan chipset IQ-M. Layar OLED 0.96", dual 18650. Tombol trigger yang nyaman untuk vaping marathon.','specs'=>'Chipset: IQ-M|Baterai: 2×18650|Output: 6-230W|Layar: 0.96" OLED|Desain: Pistol grip','price'=>695000,'price_original'=>820000,'badge'=>'sale','color_gradient'=>'grad-orange','stock'=>6,'rating'=>4.7,'review_count'=>193],
            ['name'=>'Vaporesso GEN 200 Mod','brand'=>'VAPORESSO','category'=>'mod','description'=>'Chipset AXON dengan mode Smart/RDL/DIY yang fleksibel. Layar TFT 0.91" clear, dual 18650, sisi badan anti-slip texture.','specs'=>'Chipset: AXON|Baterai: 2×18650|Output: 5-200W|Layar: 0.91" TFT|Resistance: 0.03Ω-5Ω','price'=>820000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-blue','stock'=>10,'rating'=>4.8,'review_count'=>156],
            ['name'=>'Innokin Proton Mini 120W','brand'=>'INNOKIN','category'=>'mod','description'=>'Mod kompak single 21700/18650 dengan output 120W. Desain ergonomis, layar TFT 1.45" besar dan mudah dibaca. Cocok untuk daily carry.','specs'=>'Chipset: Innokin|Baterai: 1×21700/18650|Output: 5-120W|Layar: 1.45" TFT|Charging: USB-C','price'=>565000,'price_original'=>650000,'badge'=>'sale','color_gradient'=>'grad-green','stock'=>9,'rating'=>4.6,'review_count'=>211],
            ['name'=>'Vandy Vape Pulse V3 95W','brand'=>'VANDY VAPE','category'=>'mod','description'=>'Squonk mod BF dengan botol 10ml built-in, output 95W. Sempurna untuk pengguna RDA yang ingin kenyamanan squonking.','specs'=>'Chipset: EVO75C|Baterai: 1×21700/18650|Output: 5-95W|Botol: 10ml BF|Layar: 0.96" OLED','price'=>489000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-purple','stock'=>7,'rating'=>4.7,'review_count'=>134],
            ['name'=>'Uwell Valyrian III Mod 200W','brand'=>'UWELL','category'=>'mod','description'=>'Mod premium dengan dual 18650, output 200W. Chipset UWELL generasi terbaru dengan mode TC (Ti/Ni/SS) yang akurat.','specs'=>'Chipset: UWELL Chip|Baterai: 2×18650|Output: 5-200W|Layar: 0.96" TFT|TC: Ti/Ni/SS316L','price'=>750000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-indigo','stock'=>11,'rating'=>4.8,'review_count'=>178],
            ['name'=>'Wotofo Recurve Dual Mod','brand'=>'WOTOFO','category'=>'mod','description'=>'Mod minimalis dual 18650 dengan finish carbon fiber. Ideal untuk penggunaan harian dengan desain yang slim dan ringan.','specs'=>'Baterai: 2×18650|Output: 5-200W|Layar: 0.96" TFT|Material: Carbon Fiber + Zinc Alloy|Charging: USB-C','price'=>420000,'price_original'=>480000,'badge'=>'sale','color_gradient'=>'grad-red','stock'=>14,'rating'=>4.5,'review_count'=>92],
            ['name'=>'Eleaf iStick Pico Plus 100W','brand'=>'ELEAF','category'=>'mod','description'=>'Penerus legendaris iStick Pico dengan upgrade output 100W dan layar TFT berwarna. Compact, ringan, cocok untuk traveler.','specs'=>'Baterai: 1×18650/21700|Output: 1-100W|Layar: 0.96" TFT|Ukuran: 90×45×26mm|Charging: USB-C','price'=>360000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-orange','stock'=>18,'rating'=>4.6,'review_count'=>267],
            ['name'=>'SMOK Morph 3 230W','brand'=>'SMOK','category'=>'mod','description'=>'Mod flagship SMOK dengan layar TFT 2" terbesar di kelasnya. Dual 18650, output 230W, chipset IQ-M terbaru.','specs'=>'Chipset: IQ-M|Baterai: 2×18650|Output: 5-230W|Layar: 2.0" TFT|Ukuran: 90×56×25mm','price'=>980000,'price_original'=>1150000,'badge'=>'hot','color_gradient'=>'grad-blue','stock'=>5,'rating'=>4.9,'review_count'=>312],
            ['name'=>'Geekvape Z200 Mod','brand'=>'GEEKVAPE','category'=>'mod','description'=>'Mod 200W dual 18650 dengan chipset AS Chip yang cepat. Waterproof IP68 – lebih baik dari pendahulunya Aegis X.','specs'=>'Chipset: AS Chip|Baterai: 2×18650|Output: 5-200W|Waterproof: IP68|Layar: 1.08" TFT','price'=>1100000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-green','stock'=>6,'rating'=>4.9,'review_count'=>198],
            ['name'=>'Voopoo Argus GT 2 Mod','brand'=>'VOOPOO','category'=>'mod','description'=>'Mod dual 18650 dengan chipset GENE TT dan quick-firing 0.001s. Layar 0.96" OLED dengan mode TC lengkap.','specs'=>'Chipset: GENE TT|Baterai: 2×18650|Output: 5-200W|Firing: 0.001s|Layar: 0.96" OLED','price'=>830000,'price_original'=>950000,'badge'=>'sale','color_gradient'=>'grad-purple','stock'=>9,'rating'=>4.8,'review_count'=>224],
            ['name'=>'Freemax Marvos X 100W','brand'=>'FREEMAX','category'=>'mod','description'=>'Mod 100W dengan single 21700 dan layar TFT 0.96" berwarna. Desain tubular yang unik dengan grip rubber side panel.','specs'=>'Baterai: 1×21700/18650|Output: 5-100W|Layar: 0.96" TFT|Charging: USB-C 2A|Ukuran: 127×38×28mm','price'=>495000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-indigo','stock'=>13,'rating'=>4.7,'review_count'=>143],
            ['name'=>'Rincoe Mechman 228W','brand'=>'RINCOE','category'=>'mod','description'=>'Mod dual 18650 dengan warna-warna cerah dan desain funky. Output 228W dengan chipset generasi terbaru yang stabil.','specs'=>'Baterai: 2×18650|Output: 5-228W|Layar: 0.96" TFT|TC Modes: Ni/Ti/SS|Warna: 6 pilihan','price'=>385000,'price_original'=>450000,'badge'=>'sale','color_gradient'=>'grad-orange','stock'=>20,'rating'=>4.5,'review_count'=>88],

            // ════════════════════════════════════════
            // POD SYSTEM (15 produk)
            // ════════════════════════════════════════
            ['name'=>'Vaporesso GTX ONE 40W Kit','brand'=>'VAPORESSO','category'=>'pod','description'=>'Pod system kompak 2000mAh, kapasitas cartridge 4ml, pengisian USB-C. Cocok untuk pemula maupun advanced user yang ingin portabilitas maksimal.','specs'=>'Baterai: 2000mAh|Kapasitas: 4ml|Output: 5-40W|Charging: USB-C 1A|Coil: GTX Mesh','price'=>389000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-blue','stock'=>20,'rating'=>4.8,'review_count'=>182],
            ['name'=>'SMOK NORD 5 80W','brand'=>'SMOK','category'=>'pod','description'=>'Layar OLED terbaru, baterai built-in 2000mAh, output up to 80W. Pod yang bisa dipakai MTL dan DTL secara fleksibel.','specs'=>'Baterai: 2000mAh (built-in)|Kapasitas: 6ml|Output: 5-80W|Layar: OLED|Charging: USB-C','price'=>449000,'price_original'=>580000,'badge'=>'sale','color_gradient'=>'grad-green','stock'=>18,'rating'=>4.9,'review_count'=>310],
            ['name'=>'Uwell Caliburn A3S 18W','brand'=>'UWELL','category'=>'pod','description'=>'Pod system MTL/DTL ultra-slim, kapasitas 2ml, MESH coil Pro FOCS. Desain paling tipis di kelasnya, perfect untuk pocket carry.','specs'=>'Baterai: 520mAh|Kapasitas: 2ml|Output: 5-18W|Charging: USB-C|Coil: MESH Pro FOCS','price'=>275000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-orange','stock'=>25,'rating'=>4.7,'review_count'=>156],
            ['name'=>'VOOPOO ARGUS Z 17W','brand'=>'VOOPOO','category'=>'pod','description'=>'Pod system entry level yang sempurna. Baterai 900mAh, airflow adjustable dari bawah, coil PnP-C1 dengan rasa jernih.','specs'=>'Baterai: 900mAh|Kapasitas: 2ml|Output: 11-17W|Airflow: Bottom adjustable|Coil: PnP-C1','price'=>195000,'price_original'=>245000,'badge'=>'sale','color_gradient'=>'grad-purple','stock'=>30,'rating'=>4.6,'review_count'=>421],
            ['name'=>'Geekvape Wenax M1 Pod','brand'=>'GEEKVAPE','category'=>'pod','description'=>'Pod draw-activated simpel dengan coil mesh 0.8Ω. Kapasitas 2ml, baterai 800mAh. Tidak ada tombol, cukup hisap langsung nyala.','specs'=>'Baterai: 800mAh|Kapasitas: 2ml|Coil: 0.8Ω Mesh|Aktivasi: Draw-triggered|Charging: USB-C','price'=>165000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-red','stock'=>35,'rating'=>4.5,'review_count'=>298],
            ['name'=>'Lost Vape Orion Bar 5000','brand'=>'LOST VAPE','category'=>'pod','description'=>'Pod disposable rechargeable 5000 puffs dengan baterai 650mAh. Kapasitas liquid 14ml prefilled, coil mesh untuk rasa optimal.','specs'=>'Baterai: 650mAh|Kapasitas: 14ml (prefilled)|Puffs: 5000|Koil: Mesh|Charging: USB-C','price'=>85000,'price_original'=>null,'badge'=>'hot','color_gradient'=>'grad-blue','stock'=>100,'rating'=>4.8,'review_count'=>1243],
            ['name'=>'Vaporesso XROS 4 Mini','brand'=>'VAPORESSO','category'=>'pod','description'=>'Pod MTL terbaru dari Vaporesso dengan baterai 1000mAh dan kapasitas 2ml. Refillable side-fill mudah, airflow dual adjustable.','specs'=>'Baterai: 1000mAh|Kapasitas: 2ml|Output: 11-16W|Airflow: Dual adjustable|Charging: USB-C','price'=>299000,'price_original'=>340000,'badge'=>'sale','color_gradient'=>'grad-green','stock'=>22,'rating'=>4.7,'review_count'=>187],
            ['name'=>'SMOK Novo 5 30W','brand'=>'SMOK','category'=>'pod','description'=>'Novo series terbaru dengan output 30W dan layar OLED kecil. Kapasitas 2ml, coil LP2 series untuk flavour murni.','specs'=>'Baterai: 900mAh|Kapasitas: 2ml|Output: 5-30W|Layar: OLED|Coil: LP2 Series','price'=>235000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-indigo','stock'=>19,'rating'=>4.6,'review_count'=>143],
            ['name'=>'Innokin Klypse Pod 12W','brand'=>'INNOKIN','category'=>'pod','description'=>'Pod snap-fit inovatif dengan coil yang mudah diganti tanpa tangan basah. Kapasitas 2ml, baterai 500mAh, cocok untuk pemula.','specs'=>'Baterai: 500mAh|Kapasitas: 2ml|Output: Fixed 12W|Coil: Snap-fit 1.2Ω|Charging: USB-C','price'=>185000,'price_original'=>220000,'badge'=>'sale','color_gradient'=>'grad-purple','stock'=>28,'rating'=>4.4,'review_count'=>96],
            ['name'=>'Uwell Caliburn G3 Lite','brand'=>'UWELL','category'=>'pod','description'=>'Caliburn G3 versi lite yang lebih terjangkau. Baterai 750mAh, kapasitas 2ml, airflow adjustable dengan coil G3 series.','specs'=>'Baterai: 750mAh|Kapasitas: 2ml|Output: 5-20W|Airflow: Adjustable|Coil: G3 Series','price'=>245000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-orange','stock'=>24,'rating'=>4.7,'review_count'=>209],
            ['name'=>'Elfbar BC5000 Rechargeable','brand'=>'ELFBAR','category'=>'pod','description'=>'Disposable pod rechargeable dengan 5000 puffs dan 13ml liquid prefilled. Tersedia dalam 30+ varian rasa. Baterai 650mAh USB-C.','specs'=>'Baterai: 650mAh|Kapasitas: 13ml (prefilled)|Puffs: 5000|Nicotine: 50mg|Charging: USB-C','price'=>75000,'price_original'=>null,'badge'=>'hot','color_gradient'=>'grad-blue','stock'=>200,'rating'=>4.8,'review_count'=>3421],
            ['name'=>'Voopoo Drag H40 Pod Mod','brand'=>'VOOPOO','category'=>'pod','description'=>'Pod mod hybrid 40W dengan kapasitas 4.5ml dan coil PnP. Baterai built-in 2500mAh dengan fast charging 5V/2A.','specs'=>'Baterai: 2500mAh|Kapasitas: 4.5ml|Output: 5-40W|Charging: 5V/2A|Coil: PnP Series','price'=>359000,'price_original'=>420000,'badge'=>'sale','color_gradient'=>'grad-green','stock'=>16,'rating'=>4.8,'review_count'=>274],
            ['name'=>'Geekvape Sonder Q Pod 20W','brand'=>'GEEKVAPE','category'=>'pod','description'=>'Pod ultra-compact 20W dengan kapasitas 2ml dan baterai 1000mAh. Sistem top-fill mudah dengan airflow bawah yang adjustable.','specs'=>'Baterai: 1000mAh|Kapasitas: 2ml|Output: 5-20W|Fill: Top-fill|Airflow: Bottom adjustable','price'=>215000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-red','stock'=>31,'rating'=>4.6,'review_count'=>167],
            ['name'=>'Vaporesso Eco Nano Pro','brand'=>'VAPORESSO','category'=>'pod','description'=>'Pod nano terkecil dari Vaporesso. Baterai 1000mAh, kapasitas 6ml besar untuk ukurannya, coil mesh GTX untuk cloud maksimal.','specs'=>'Baterai: 1000mAh|Kapasitas: 6ml|Output: 5-25W|Koil: GTX Mesh|Ukuran: 59×28×16mm','price'=>279000,'price_original'=>320000,'badge'=>'new','color_gradient'=>'grad-indigo','stock'=>27,'rating'=>4.7,'review_count'=>198],
            ['name'=>'SMOK RPM 5 60W Kit','brand'=>'SMOK','category'=>'pod','description'=>'Pod kit 60W dengan baterai built-in 2000mAh dan kapasitas pod 6.5ml terbesar. Layar TFT 0.69", coil RPM terbaru.','specs'=>'Baterai: 2000mAh|Kapasitas: 6.5ml|Output: 5-60W|Layar: 0.69" TFT|Coil: RPM Series','price'=>395000,'price_original'=>460000,'badge'=>'hot','color_gradient'=>'grad-purple','stock'=>13,'rating'=>4.8,'review_count'=>321],

            // ════════════════════════════════════════
            // LIQUID (18 produk)
            // ════════════════════════════════════════
            ['name'=>'Tropical Blast Saltnic 30ml','brand'=>'SaltNic Pro','category'=>'liquid','description'=>'Perpaduan buah tropis segar — mangga matang, nanas, dan pepaya. Smooth throat hit yang khas salt nicotine. Cocok untuk pod system MTL.','specs'=>'Volume: 30ml|Nicotine: 25mg / 50mg|VG/PG: 50/50|Type: Salt Nicotine|Rasa: Tropical Fruit','price'=>85000,'price_original'=>null,'badge'=>'hot','color_gradient'=>'grad-green','stock'=>50,'rating'=>4.8,'review_count'=>534],
            ['name'=>'Mixed Berry Ice 60ml','brand'=>'Naked 100','category'=>'liquid','description'=>'Campuran blueberry, raspberry, dan blackcurrant dengan sensasi dingin menthol yang menyegarkan. Best seller Naked 100 sepanjang masa.','specs'=>'Volume: 60ml|Nicotine: 0mg / 3mg / 6mg|VG/PG: 70/30|Type: Freebase|Rasa: Berry Menthol','price'=>145000,'price_original'=>165000,'badge'=>'hot','color_gradient'=>'grad-indigo','stock'=>40,'rating'=>4.9,'review_count'=>712],
            ['name'=>'Arctic Menthol Saltnic 30ml','brand'=>'Polar Ice','category'=>'liquid','description'=>'Menthol murni double hit dengan efek dingin maksimal. Formula ice blast untuk sensasi paling segar, cocok untuk cuaca panas.','specs'=>'Volume: 30ml|Nicotine: 25mg / 50mg|VG/PG: 50/50|Type: Salt Nicotine|Rasa: Pure Menthol','price'=>95000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-blue','stock'=>35,'rating'=>4.7,'review_count'=>289],
            ['name'=>'Vanilla Custard 60ml','brand'=>'Cuttwood','category'=>'liquid','description'=>'Custard vanila yang kaya dan creamy dengan aroma roti panggang yang halus. Rasa dessert terpopuler dari brand premium asal Amerika.','specs'=>'Volume: 60ml|Nicotine: 0mg / 3mg / 6mg|VG/PG: 70/30|Type: Freebase|Rasa: Creamy Dessert','price'=>165000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-orange','stock'=>22,'rating'=>4.8,'review_count'=>445],
            ['name'=>'Lychee Ice Saltnic 30ml','brand'=>'Monster Bars','category'=>'liquid','description'=>'Rasa lychee segar dan manis dengan sentuhan es yang dingin di akhir. Salah satu varian saltnic paling populer di kalangan vapers Indonesia.','specs'=>'Volume: 30ml|Nicotine: 25mg / 50mg|VG/PG: 50/50|Type: Salt Nicotine|Rasa: Lychee Ice','price'=>90000,'price_original'=>105000,'badge'=>'sale','color_gradient'=>'grad-purple','stock'=>45,'rating'=>4.9,'review_count'=>891],
            ['name'=>'Strawberry Kiwi Saltnic 30ml','brand'=>'Pachamama','category'=>'liquid','description'=>'Perpaduan strawberry merah matang dengan kiwi yang sedikit asam. Balance rasa sempurna, tidak terlalu manis juga tidak terlalu asam.','specs'=>'Volume: 30ml|Nicotine: 25mg / 50mg|VG/PG: 50/50|Type: Salt Nicotine|Rasa: Strawberry Kiwi','price'=>88000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-red','stock'=>38,'rating'=>4.7,'review_count'=>367],
            ['name'=>'Watermelon Ice 60ml','brand'=>'Juice Head','category'=>'liquid','description'=>'Semangka segar dengan lapisan es yang tebal. Rasa freebase klasik yang memuaskan untuk cloud chasing di musim panas.','specs'=>'Volume: 60ml|Nicotine: 0mg / 3mg / 6mg|VG/PG: 70/30|Type: Freebase|Rasa: Watermelon Ice','price'=>150000,'price_original'=>170000,'badge'=>'sale','color_gradient'=>'grad-green','stock'=>29,'rating'=>4.8,'review_count'=>523],
            ['name'=>'Caramel Tobacco 60ml','brand'=>'Black Note','category'=>'liquid','description'=>'Tembakau premium dengan lapisan karamel yang halus dan manis. Rasa tobacco yang paling smooth di pasaran, tidak pedih di tenggorokan.','specs'=>'Volume: 60ml|Nicotine: 3mg / 6mg / 12mg|VG/PG: 70/30|Type: Freebase|Rasa: Tobacco Caramel','price'=>175000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-orange','stock'=>19,'rating'=>4.8,'review_count'=>412],
            ['name'=>'Grape Ice Saltnic 30ml','brand'=>'BLVK Unicorn','category'=>'liquid','description'=>'Anggur merah dan anggur hitam dengan perpaduan es yang menyegarkan. Rasa grape paling autentik yang pernah ada di pasar saltnic.','specs'=>'Volume: 30ml|Nicotine: 30mg / 50mg|VG/PG: 50/50|Type: Salt Nicotine|Rasa: Grape Ice','price'=>92000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-purple','stock'=>42,'rating'=>4.7,'review_count'=>278],
            ['name'=>'Peach Mango Watermelon 60ml','brand'=>'Pachamama','category'=>'liquid','description'=>'Triple fruit blend yang paling dicari — persik, mangga, dan semangka dalam satu botol 60ml. Balance sempurna antara manis dan segar.','specs'=>'Volume: 60ml|Nicotine: 0mg / 3mg / 6mg|VG/PG: 70/30|Type: Freebase|Rasa: Triple Fruit','price'=>160000,'price_original'=>185000,'badge'=>'hot','color_gradient'=>'grad-indigo','stock'=>33,'rating'=>4.9,'review_count'=>647],
            ['name'=>'Mango Peach Pineapple Saltnic','brand'=>'Juice Head','category'=>'liquid','description'=>'3-in-1 tropical fusion. Mangga harum, persik manis, dan nanas yang segar. Tersedia dalam 30ml saltnic dan 60ml freebase.','specs'=>'Volume: 30ml|Nicotine: 25mg / 50mg|VG/PG: 50/50|Type: Salt Nicotine|Rasa: Tropical Fusion','price'=>95000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-orange','stock'=>36,'rating'=>4.8,'review_count'=>489],
            ['name'=>'Blue Razz Lemonade 60ml','brand'=>'Twist E-Liquids','category'=>'liquid','description'=>'Raspberry biru dengan lemonade segar yang sedikit asam. Rasa yang unik dan refreshing, cocok untuk semua jenis setup.','specs'=>'Volume: 60ml|Nicotine: 0mg / 3mg / 6mg|VG/PG: 70/30|Type: Freebase|Rasa: Blue Raspberry Lemonade','price'=>155000,'price_original'=>175000,'badge'=>'sale','color_gradient'=>'grad-blue','stock'=>27,'rating'=>4.6,'review_count'=>334],
            ['name'=>'Honeydew Melon Berry 60ml','brand'=>'Naked 100','category'=>'liquid','description'=>'Melon honeydew matang dipadukan dengan campuran beri segar. Salah satu varian Naked 100 yang paling smooth dan aromatic.','specs'=>'Volume: 60ml|Nicotine: 0mg / 3mg|VG/PG: 70/30|Type: Freebase|Rasa: Melon Berry','price'=>148000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-green','stock'=>24,'rating'=>4.7,'review_count'=>298],
            ['name'=>'Banana Ice Saltnic 30ml','brand'=>'Cush Man','category'=>'liquid','description'=>'Pisang matang yang creamy dengan blast menthol yang kuat. Rasa dessert sekaligus fresh yang sempurna untuk sepanjang hari.','specs'=>'Volume: 30ml|Nicotine: 25mg / 50mg|VG/PG: 50/50|Type: Salt Nicotine|Rasa: Banana Ice','price'=>87000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-orange','stock'=>41,'rating'=>4.7,'review_count'=>356],
            ['name'=>'Dragon Fruit Lychee 30ml','brand'=>'Innevape','category'=>'liquid','description'=>'Buah naga eksotis dipadukan dengan lychee manis. Rasa yang unik dan berbeda dari saltnic biasanya, layak dicoba bagi pecinta rasa eksotis.','specs'=>'Volume: 30ml|Nicotine: 25mg / 50mg|VG/PG: 50/50|Type: Salt Nicotine|Rasa: Dragon Fruit Lychee','price'=>93000,'price_original'=>108000,'badge'=>'sale','color_gradient'=>'grad-red','stock'=>31,'rating'=>4.8,'review_count'=>412],
            ['name'=>'Strawberry Cheesecake 60ml','brand'=>'The Milkman','category'=>'liquid','description'=>'Cheesecake creamy dengan topping strawberry segar. Rasa dessert premium yang cocok untuk DTL setup dengan coil kanthal.','specs'=>'Volume: 60ml|Nicotine: 0mg / 3mg / 6mg|VG/PG: 75/25|Type: Freebase HVG|Rasa: Dessert Cheesecake','price'=>178000,'price_original'=>200000,'badge'=>'hot','color_gradient'=>'grad-purple','stock'=>18,'rating'=>4.9,'review_count'=>567],
            ['name'=>'Apple Peach Saltnic 30ml','brand'=>'Air Factory','category'=>'liquid','description'=>'Apel merah segar dengan persik yang matang dan manis. Rasa buah yang natural dan tidak artificial, smooth di tenggorokan.','specs'=>'Volume: 30ml|Nicotine: 25mg / 50mg|VG/PG: 50/50|Type: Salt Nicotine|Rasa: Apple Peach','price'=>89000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-indigo','stock'=>44,'rating'=>4.6,'review_count'=>223],
            ['name'=>'Pineapple Coconut Ice 60ml','brand'=>'Keep It 100','category'=>'liquid','description'=>'Piña colada tanpa alkohol — nanas segar dan kelapa creamy dengan sensasi es di akhir. Rasa pantai yang menyegarkan.','specs'=>'Volume: 60ml|Nicotine: 0mg / 3mg / 6mg|VG/PG: 70/30|Type: Freebase|Rasa: Tropical Ice','price'=>152000,'price_original'=>168000,'badge'=>'new','color_gradient'=>'grad-blue','stock'=>26,'rating'=>4.7,'review_count'=>301],

            // ════════════════════════════════════════
            // COIL (15 produk)
            // ════════════════════════════════════════
            ['name'=>'VOOPOO PnP VM1 Coil 0.3Ω (5pcs)','brand'=>'VOOPOO','category'=>'coil','description'=>'Coil pengganti PnP VM1 0.3Ω mesh untuk VOOPOO Drag S, Drag X, Argus, dan VINCI series. Flavour jernih dengan cloud yang tebal.','specs'=>'Tipe: PnP VM1|Resistance: 0.3Ω|Rekomendasi: 32-40W|Kompatibel: Drag S/X/Argus/VINCI|Isi: 5pcs','price'=>120000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-red','stock'=>60,'rating'=>4.8,'review_count'=>876],
            ['name'=>'VOOPOO PnP TW15 Coil 0.2Ω (5pcs)','brand'=>'VOOPOO','category'=>'coil','description'=>'Coil terbaru PnP TW15 twisted wire 0.2Ω untuk pengalaman DTL maksimal. Output 60-80W dengan flavour luar biasa jernih.','specs'=>'Tipe: PnP TW15|Resistance: 0.2Ω|Rekomendasi: 60-80W|Material: Twisted Wire|Isi: 5pcs','price'=>135000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-purple','stock'=>45,'rating'=>4.7,'review_count'=>234],
            ['name'=>'SMOK LP2 Meshed 0.23Ω (5pcs)','brand'=>'SMOK','category'=>'coil','description'=>'Coil LP2 Meshed 0.23Ω untuk SMOK Novo 5 dan SMOK RPM 5. Teknologi mesh terbaru SMOK dengan rasa yang konsisten.','specs'=>'Tipe: LP2 Meshed|Resistance: 0.23Ω|Rekomendasi: 25-30W|Kompatibel: Novo 5/RPM 5|Isi: 5pcs','price'=>110000,'price_original'=>125000,'badge'=>'sale','color_gradient'=>'grad-blue','stock'=>55,'rating'=>4.6,'review_count'=>312],
            ['name'=>'Uwell Caliburn G2 Coil 1.2Ω (4pcs)','brand'=>'UWELL','category'=>'coil','description'=>'Replacement coil untuk Caliburn G2 dan Caliburn GK2. Resistance 1.2Ω untuk MTL vaping dengan rasa paling jernih.','specs'=>'Tipe: UN2 Meshed|Resistance: 1.2Ω|Rekomendasi: 12-18W|Kompatibel: Caliburn G2/GK2|Isi: 4pcs','price'=>95000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-orange','stock'=>70,'rating'=>4.8,'review_count'=>1023],
            ['name'=>'Vaporesso GTX Coil 0.6Ω (5pcs)','brand'=>'VAPORESSO','category'=>'coil','description'=>'GTX Coil 0.6Ω mesh untuk GTX ONE, GTX 18, GTX 22. Versatile coil yang bisa dipakai MTL maupun DTL tergantung airflow.','specs'=>'Tipe: GTX Mesh|Resistance: 0.6Ω|Rekomendasi: 20-28W|Kompatibel: GTX Series|Isi: 5pcs','price'=>105000,'price_original'=>115000,'badge'=>'sale','color_gradient'=>'grad-green','stock'=>52,'rating'=>4.7,'review_count'=>445],
            ['name'=>'Geekvape B Series Coil 0.2Ω (5pcs)','brand'=>'GEEKVAPE','category'=>'coil','description'=>'Coil B series untuk Geekvape Aegis Boost dan Zeus sub-ohm. Material SS316L dengan flavour yang kaya dan cloud besar.','specs'=>'Tipe: B Series Mesh|Resistance: 0.2Ω|Rekomendasi: 50-80W|Material: SS316L|Isi: 5pcs','price'=>125000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-indigo','stock'=>38,'rating'=>4.8,'review_count'=>567],
            ['name'=>'Freemax Mesh Pro Coil 0.15Ω (3pcs)','brand'=>'FREEMAX','category'=>'coil','description'=>'Coil triple mesh flagship dari Freemax. 0.15Ω untuk cloud maksimal dan flavour terkaya. Kompatibel dengan Freemax Fireluke 3 dan 4.','specs'=>'Tipe: Triple Mesh|Resistance: 0.15Ω|Rekomendasi: 60-100W|Kompatibel: Fireluke 3/4|Isi: 3pcs','price'=>145000,'price_original'=>165000,'badge'=>'hot','color_gradient'=>'grad-purple','stock'=>28,'rating'=>4.9,'review_count'=>389],
            ['name'=>'Aspire BP Coil 0.17Ω (5pcs)','brand'=>'ASPIRE','category'=>'coil','description'=>'Aspire BP coil mesh ultra-low resistance untuk cloud chasing. Kompatibel dengan Aspire BP 60 dan BP80 series.','specs'=>'Tipe: BP Mesh|Resistance: 0.17Ω|Rekomendasi: 35-45W|Kompatibel: BP60/BP80|Isi: 5pcs','price'=>100000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-red','stock'=>43,'rating'=>4.6,'review_count'=>198],
            ['name'=>'Horizontech Falcon King M2 (3pcs)','brand'=>'HORIZONTECH','category'=>'coil','description'=>'Coil M2 mesh premium untuk Falcon King tank. Teknologi wood pulp cotton untuk flavour terbaik tanpa rasa terbakar.','specs'=>'Tipe: M2 Mesh|Resistance: 0.16Ω|Rekomendasi: 40-80W|Cotton: Wood Pulp|Isi: 3pcs','price'=>155000,'price_original'=>175000,'badge'=>'sale','color_gradient'=>'grad-orange','stock'=>22,'rating'=>4.8,'review_count'=>267],
            ['name'=>'Innokin Plex3D Coil 0.15Ω (3pcs)','brand'=>'INNOKIN','category'=>'coil','description'=>'Coil Plex3D terbaru Innokin dengan tekstur mesh yang unik berbentuk 3D. Mengeluarkan flavour yang sangat intensif dan cloud besar.','specs'=>'Tipe: Plex3D Mesh|Resistance: 0.15Ω|Rekomendasi: 60-80W|Kompatibel: Zenith Pro|Isi: 3pcs','price'=>130000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-blue','stock'=>31,'rating'=>4.7,'review_count'=>178],
            ['name'=>'Eleaf GTL Coil 0.6Ω (5pcs)','brand'=>'ELEAF','category'=>'coil','description'=>'GTL Pod coil untuk Eleaf Kits dengan resistance 0.6Ω. Kompak dan mudah dipasang, rasa bersih tanpa break-in lama.','specs'=>'Tipe: GTL Pod|Resistance: 0.6Ω|Rekomendasi: 10-18W|Kompatibel: Eleaf GTL Pod|Isi: 5pcs','price'=>85000,'price_original'=>95000,'badge'=>'sale','color_gradient'=>'grad-green','stock'=>48,'rating'=>4.5,'review_count'=>134],
            ['name'=>'SMOK TF Coil T8 0.15Ω (3pcs)','brand'=>'SMOK','category'=>'coil','description'=>'Coil T8 octuple mesh dari SMOK untuk TF tank. Delapan kawat mesh dalam satu koil untuk rasa dan cloud yang tak tertandingi.','specs'=>'Tipe: T8 Octuple Mesh|Resistance: 0.15Ω|Rekomendasi: 70-120W|Kompatibel: TF Tank|Isi: 3pcs','price'=>140000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-indigo','stock'=>19,'rating'=>4.8,'review_count'=>223],
            ['name'=>'Wotofo NexMesh Coil 0.13Ω (5pcs)','brand'=>'WOTOFO','category'=>'coil','description'=>'Mesh premium Wotofo dengan resistance 0.13Ω super rendah. Untuk pengguna high-power yang ingin cloud maksimal.','specs'=>'Tipe: NexMesh|Resistance: 0.13Ω|Rekomendasi: 80-100W|Material: NexMesh|Isi: 5pcs','price'=>128000,'price_original'=>145000,'badge'=>'sale','color_gradient'=>'grad-purple','stock'=>26,'rating'=>4.7,'review_count'=>189],
            ['name'=>'Uwell Crown 5 Coil 0.23Ω (4pcs)','brand'=>'UWELL','category'=>'coil','description'=>'Coil FeCrAl mesh untuk UWELL Crown 5 tank. Teknologi Self-Cleaning coating untuk umur coil yang lebih panjang.','specs'=>'Tipe: FeCrAl Mesh|Resistance: 0.23Ω|Rekomendasi: 40-60W|Fitur: Self-Cleaning|Isi: 4pcs','price'=>118000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-red','stock'=>35,'rating'=>4.8,'review_count'=>312],
            ['name'=>'Vandy Vape Kylin M Coil 0.16Ω (5pcs)','brand'=>'VANDY VAPE','category'=>'coil','description'=>'Coil mesh untuk Kylin M RTA/RDTA. Mesh aramid fiber tahan panas tinggi dengan rasa yang konsisten dan umur panjang.','specs'=>'Tipe: Aramid Fiber Mesh|Resistance: 0.16Ω|Rekomendasi: 50-80W|Kompatibel: Kylin M|Isi: 5pcs','price'=>135000,'price_original'=>150000,'badge'=>'new','color_gradient'=>'grad-orange','stock'=>29,'rating'=>4.7,'review_count'=>156],

            // ════════════════════════════════════════
            // STARTER KIT (15 produk)
            // ════════════════════════════════════════
            ['name'=>'SMOK Starter Bundle Kit','brand'=>'SMOK','category'=>'starter','description'=>'Bundle lengkap untuk pemula: SMOK NORD 5 + 2 pod cartridge + 3 coil pengganti + USB-C cable + liquid starter 30ml gratis!','specs'=>'Isi: 1× NORD 5 Pod|2× Cartridge 6ml|3× Replacement Coil|1× USB-C Cable|1× Liquid 30ml','price'=>589000,'price_original'=>750000,'badge'=>'sale','color_gradient'=>'grad-green','stock'=>10,'rating'=>4.9,'review_count'=>128],
            ['name'=>'Vaporesso GTX Starter Pack','brand'=>'VAPORESSO','category'=>'starter','description'=>'Paket terlengkap untuk vaper baru. GTX ONE 40W Kit + 2 coil GTX + liquid 30ml pilihan + leather case eksklusif.','specs'=>'Isi: 1× GTX ONE Kit|2× GTX Coil|1× Liquid 30ml|1× Leather Case|Warranty: 6 bulan','price'=>649000,'price_original'=>820000,'badge'=>'hot','color_gradient'=>'grad-blue','stock'=>8,'rating'=>4.9,'review_count'=>94],
            ['name'=>'VOOPOO Beginner Complete Set','brand'=>'VOOPOO','category'=>'starter','description'=>'Set pemula VOOPOO dengan ARGUS Z Pod + 5 PnP coil + 2 liquid saltnic 30ml + charger dock eksklusif.','specs'=>'Isi: 1× ARGUS Z Pod|5× PnP Coil|2× Liquid 30ml|1× Dock Charger|Warranty: 6 bulan','price'=>425000,'price_original'=>560000,'badge'=>'sale','color_gradient'=>'grad-purple','stock'=>12,'rating'=>4.8,'review_count'=>76],
            ['name'=>'Uwell Caliburn MTL Starter','brand'=>'UWELL','category'=>'starter','description'=>'Starter kit MTL terbaik. Caliburn A3S + 8 coil (UN1 & UN2) + 3 liquid saltnic + cleaning kit.','specs'=>'Isi: 1× Caliburn A3S|8× Coil Mixed|3× Liquid Saltnic 30ml|1× Cleaning Kit|Warranty: 6 bulan','price'=>519000,'price_original'=>650000,'badge'=>'hot','color_gradient'=>'grad-orange','stock'=>9,'rating'=>4.9,'review_count'=>112],
            ['name'=>'Geekvape Aegis Outdoorsman Kit','brand'=>'GEEKVAPE','category'=>'starter','description'=>'Kit outdoor lengkap. Aegis X 200W + Zeus Sub-Ohm Tank + 10 coil + 2 liquid 60ml freebase + case waterproof.','specs'=>'Isi: 1× Aegis X Mod|1× Zeus Tank|10× Coil|2× Liquid 60ml|1× Waterproof Case','price'=>1650000,'price_original'=>2100000,'badge'=>'sale','color_gradient'=>'grad-red','stock'=>5,'rating'=>4.9,'review_count'=>43],
            ['name'=>'Innokin First Vape Bundle','brand'=>'INNOKIN','category'=>'starter','description'=>'Bundle khusus pertama kali vaping. Klypse Pod + 6 snap-fit coil + 2 liquid 30ml + panduan vaping untuk pemula.','specs'=>'Isi: 1× Klypse Pod|6× Coil|2× Liquid 30ml|1× Vaping Guide|Warranty: 12 bulan','price'=>349000,'price_original'=>450000,'badge'=>'new','color_gradient'=>'grad-green','stock'=>15,'rating'=>4.7,'review_count'=>58],
            ['name'=>'Elfbar Disposable Variety Pack','brand'=>'ELFBAR','category'=>'starter','description'=>'Isi 5 Elfbar BC5000 varian rasa berbeda. Hemat 20% dibanding beli satu-satu. Perfect untuk coba-coba rasa baru.','specs'=>'Isi: 5× Elfbar BC5000|Varian: Berbeda-beda|Puffs: 5000/unit|Charging: USB-C|Total: 25.000 puffs','price'=>349000,'price_original'=>425000,'badge'=>'hot','color_gradient'=>'grad-indigo','stock'=>25,'rating'=>4.8,'review_count'=>234],
            ['name'=>'Lost Vape Premium Starter Set','brand'=>'LOST VAPE','category'=>'starter','description'=>'Premium starter set dengan Orion S Pod + 3 Orion coil + leather pouch premium + 2 liquid saltnic pilihan.','specs'=>'Isi: 1× Orion S Pod|3× Orion Coil|1× Leather Pouch|2× Liquid Saltnic 30ml|Warranty: 6 bulan','price'=>789000,'price_original'=>950000,'badge'=>'sale','color_gradient'=>'grad-purple','stock'=>7,'rating'=>4.9,'review_count'=>67],
            ['name'=>'SMOK RPM Flavor Chaser Kit','brand'=>'SMOK','category'=>'starter','description'=>'Kit untuk penggemar flavour. RPM 5 60W + 3 RPM coil + 4 liquid freebase 60ml berbeda rasa + coil priming station.','specs'=>'Isi: 1× RPM 5 Kit|3× RPM Coil|4× Liquid 60ml|1× Priming Station|Warranty: 6 bulan','price'=>849000,'price_original'=>1050000,'badge'=>'hot','color_gradient'=>'grad-blue','stock'=>6,'rating'=>4.9,'review_count'=>89],
            ['name'=>'Vaporesso XROS Travel Kit','brand'=>'VAPORESSO','category'=>'starter','description'=>'Travel kit kompak. XROS 4 Mini + 2 pod tambahan + 3 liquid saltnic 30ml + travel case canvas eksklusif + cable.','specs'=>'Isi: 1× XROS 4 Mini|2× Pod Cartridge|3× Liquid 30ml|1× Canvas Travel Case|1× USB-C Cable','price'=>559000,'price_original'=>700000,'badge'=>'new','color_gradient'=>'grad-orange','stock'=>11,'rating'=>4.8,'review_count'=>73],
            ['name'=>'Beginner Salt Nic Starter Pack','brand'=>'Multi Brand','category'=>'starter','description'=>'Paket spesial untuk yang baru beralih dari rokok. Caliburn G3 Lite + 6 coil + 5 liquid saltnic berbeda rasa + booklet tips quit smoking.','specs'=>'Isi: 1× Caliburn G3 Lite|6× Coil|5× Liquid Saltnic|1× Tips Booklet|Warranty: 6 bulan','price'=>479000,'price_original'=>600000,'badge'=>'sale','color_gradient'=>'grad-green','stock'=>14,'rating'=>4.8,'review_count'=>198],
            ['name'=>'DTL Cloud Chaser Bundle','brand'=>'Multi Brand','category'=>'starter','description'=>'Bundle untuk cloud chaser. SMOK Morph 3 230W + Zeus Mesh Tank + 6 coil mesh + 3 liquid freebase HVG + cotton premium.','specs'=>'Isi: 1× Morph 3 Mod|1× Zeus Tank|6× Coil|3× Liquid HVG 60ml|50g Japanese Cotton','price'=>1299000,'price_original'=>1650000,'badge'=>'hot','color_gradient'=>'grad-indigo','stock'=>4,'rating'=>4.9,'review_count'=>52],
            ['name'=>'Voopoo All-In-One Starter','brand'=>'VOOPOO','category'=>'starter','description'=>'Semua yang dibutuhkan dalam satu kotak. DRAG H40 Pod Mod + 4 PnP coil + 2 liquid freebase + 1 liquid saltnic + charging cable.','specs'=>'Isi: 1× DRAG H40|4× PnP Coil|2× Liquid Freebase 60ml|1× Liquid Saltnic 30ml|1× Cable','price'=>619000,'price_original'=>780000,'badge'=>'new','color_gradient'=>'grad-red','stock'=>10,'rating'=>4.8,'review_count'=>86],
            ['name'=>'Geekvape Wenax Newbie Kit','brand'=>'GEEKVAPE','category'=>'starter','description'=>'Kit paling simpel untuk pemula total. Wenax M1 draw-activated + 4 coil pengganti + 3 liquid + manual tutorial bahasa Indonesia.','specs'=>'Isi: 1× Wenax M1|4× Coil 0.8Ω|3× Liquid 30ml|1× Tutorial ID|Warranty: 6 bulan','price'=>389000,'price_original'=>490000,'badge'=>'sale','color_gradient'=>'grad-purple','stock'=>18,'rating'=>4.7,'review_count'=>134],
            ['name'=>'Premium Gift Box Vape Set','brand'=>'VapeCloud Exclusive','category'=>'starter','description'=>'Gift set eksklusif VapeCloud untuk hadiah. Box premium berisi Lost Vape Orion Bar + 5 Elfbar berbeda rasa + 3 liquid saltnic premium + kartu ucapan.','specs'=>'Isi: 1× Orion Bar Pod|5× Elfbar BC5000|3× Liquid Saltnic Premium|1× Gift Card|Packaging: Premium Box','price'=>599000,'price_original'=>750000,'badge'=>'new','color_gradient'=>'grad-orange','stock'=>20,'rating'=>4.9,'review_count'=>47],

            // ════════════════════════════════════════
            // BATTERY (15 produk)
            // ════════════════════════════════════════
            ['name'=>'Samsung 30Q 18650 3000mAh (2pcs)','brand'=>'SAMSUNG SDI','category'=>'battery','description'=>'Baterai 18650 terpercaya untuk mod vape. Kapasitas 3000mAh, continuous discharge 15A. Standar industri untuk dual-batt mod.','specs'=>'Kapasitas: 3000mAh|Discharge: 15A continuous|Ukuran: 18650|Tegangan: 3.7V|Isi: 2pcs','price'=>145000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-green','stock'=>80,'rating'=>4.9,'review_count'=>1234],
            ['name'=>'LG HG2 18650 3000mAh (2pcs)','brand'=>'LG Chem','category'=>'battery','description'=>'LG HG2 adalah salah satu baterai 18650 terbaik untuk vaping. 3000mAh, 20A CDR, sangat cocok untuk dual-battery mod high-power.','specs'=>'Kapasitas: 3000mAh|Discharge: 20A CDR|Ukuran: 18650|Tegangan: 3.7V|Isi: 2pcs','price'=>155000,'price_original'=>165000,'badge'=>'hot','color_gradient'=>'grad-blue','stock'=>65,'rating'=>4.9,'review_count'=>987],
            ['name'=>'Sony VTC6 18650 3000mAh (2pcs)','brand'=>'Sony','category'=>'battery','description'=>'Sony VTC6 — high-drain battery terbaik dari Sony. 3000mAh, 15A CDR, dengan internal resistance sangat rendah untuk firing cepat.','specs'=>'Kapasitas: 3000mAh|Discharge: 15A CDR|Ukuran: 18650|Internal R: <25mΩ|Isi: 2pcs','price'=>160000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-red','stock'=>52,'rating'=>4.9,'review_count'=>876],
            ['name'=>'Molicel P26A 18650 2600mAh (2pcs)','brand'=>'Molicel','category'=>'battery','description'=>'Molicel P26A high-power battery dengan CDR 35A tertinggi di kelas 18650. Untuk setup single-batt dengan output ekstrem.','specs'=>'Kapasitas: 2600mAh|Discharge: 35A CDR|Ukuran: 18650|Tegangan: 3.7V|Isi: 2pcs','price'=>175000,'price_original'=>190000,'badge'=>'new','color_gradient'=>'grad-purple','stock'=>40,'rating'=>4.8,'review_count'=>445],
            ['name'=>'Samsung 40T 21700 4000mAh (2pcs)','brand'=>'SAMSUNG SDI','category'=>'battery','description'=>'Baterai 21700 terbaik untuk mod single-battery. 4000mAh dengan CDR 35A dan kapasitas terbesar di kelasnya.','specs'=>'Kapasitas: 4000mAh|Discharge: 35A CDR|Ukuran: 21700|Tegangan: 3.7V|Isi: 2pcs','price'=>195000,'price_original'=>null,'badge'=>'hot','color_gradient'=>'grad-orange','stock'=>35,'rating'=>4.9,'review_count'=>567],
            ['name'=>'LG M50LT 21700 5000mAh (2pcs)','brand'=>'LG Chem','category'=>'battery','description'=>'LG 21700 dengan kapasitas terbesar 5000mAh untuk vaping marathon. CDR 10A, cocok untuk mod regulasi wattage rendah-menengah.','specs'=>'Kapasitas: 5000mAh|Discharge: 10A CDR|Ukuran: 21700|Tegangan: 3.7V|Isi: 2pcs','price'=>205000,'price_original'=>225000,'badge'=>'sale','color_gradient'=>'grad-indigo','stock'=>28,'rating'=>4.8,'review_count'=>312],
            ['name'=>'Efest IMR 18650 3500mAh (2pcs)','brand'=>'EFEST','category'=>'battery','description'=>'Alternatif terjangkau dengan kualitas baik. IMR 18650 3500mAh dengan CDR 10A, dilengkapi proteksi internal.','specs'=>'Kapasitas: 3500mAh|Discharge: 10A CDR|Ukuran: 18650|Proteksi: Internal|Isi: 2pcs','price'=>120000,'price_original'=>140000,'badge'=>'sale','color_gradient'=>'grad-green','stock'=>70,'rating'=>4.5,'review_count'=>234],
            ['name'=>'Nitecore SC4 Smart Charger','brand'=>'NITECORE','category'=>'battery','description'=>'Charger cerdas 4-slot dengan display LCD. Kompatibel 18650, 20700, 21700, 26650. Charging current adjustable 0.3A–3A per slot.','specs'=>'Slot: 4 slots|Kompatibel: 18650/20700/21700/26650|Max Current: 3A/slot|Display: LCD|Input: AC+DC','price'=>385000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-red','stock'=>22,'rating'=>4.9,'review_count'=>456],
            ['name'=>'XTAR VC4SL Charger','brand'=>'XTAR','category'=>'battery','description'=>'Charger 4-slot dengan kabel USB-C dan display OLED. Charging speed adjustable, cocok untuk semua ukuran baterai Li-ion.','specs'=>'Slot: 4 slots|Kompatibel: 18650/21700/26650|Input: USB-C|Display: OLED|Isi: 1 charger','price'=>295000,'price_original'=>340000,'badge'=>'new','color_gradient'=>'grad-blue','stock'=>18,'rating'=>4.8,'review_count'=>189],
            ['name'=>'Golisi S2 Dual Bay Charger','brand'=>'GOLISI','category'=>'battery','description'=>'Charger dual-bay entry level yang handal. Kompatibel dengan semua baterai 18650, 20700, 21700. Dilengkapi proteksi overcharge.','specs'=>'Slot: 2 slots|Kompatibel: 18650/21700|Charging: 2A|Proteksi: Overcharge/Short|Input: USB Micro','price'=>165000,'price_original'=>185000,'badge'=>'sale','color_gradient'=>'grad-purple','stock'=>38,'rating'=>4.6,'review_count'=>267],
            ['name'=>'Samsung 25R 18650 2500mAh (4pcs)','brand'=>'SAMSUNG SDI','category'=>'battery','description'=>'Samsung 25R bundle isi 4 pcs — hemat untuk pengguna dual-battery mod dengan 2 set baterai sekaligus. CDR 20A.','specs'=>'Kapasitas: 2500mAh|Discharge: 20A CDR|Ukuran: 18650|Bundle: 4pcs|Hemat: 15% vs satuan','price'=>255000,'price_original'=>300000,'badge'=>'sale','color_gradient'=>'grad-orange','stock'=>45,'rating'=>4.8,'review_count'=>378],
            ['name'=>'Vapcell INR 20700 4000mAh (2pcs)','brand'=>'VAPCELL','category'=>'battery','description'=>'Baterai 20700 high-drain untuk mod yang membutuhkan power besar. 4000mAh CDR 30A — performa lebih baik dari 18650 biasa.','specs'=>'Kapasitas: 4000mAh|Discharge: 30A CDR|Ukuran: 20700|Tegangan: 3.7V|Isi: 2pcs','price'=>185000,'price_original'=>null,'badge'=>'new','color_gradient'=>'grad-indigo','stock'=>29,'rating'=>4.7,'review_count'=>156],
            ['name'=>'Silicone Battery Case 2-Slot','brand'=>'Generic Premium','category'=>'battery','description'=>'Case baterai silikon premium isi 2 slot. Melindungi baterai dari gesekan, kelembapan, dan short circuit. Warna random.','specs'=>'Slot: 2 baterai|Material: Food-grade Silicone|Kompatibel: 18650/20700/21700|Tebal: 3mm|Warna: Random','price'=>25000,'price_original'=>null,'badge'=>null,'color_gradient'=>'grad-red','stock'=>150,'rating'=>4.5,'review_count'=>892],
            ['name'=>'Opus BT-C3100 V2.2 Charger','brand'=>'OPUS','category'=>'battery','description'=>'Charger 4-slot profesional dengan LCD display dan function discharge/test kapasitas baterai. Untuk maintenance baterai maksimal.','specs'=>'Slot: 4 slots|Fungsi: Charge/Discharge/Test|Display: LCD|Max Current: 1A|Kompatibel: 18650-26650','price'=>445000,'price_original'=>510000,'badge'=>'hot','color_gradient'=>'grad-green','stock'=>12,'rating'=>4.9,'review_count'=>234],
            ['name'=>'Molicel P45B 21700 4500mAh (2pcs)','brand'=>'Molicel','category'=>'battery','description'=>'Baterai 21700 premium terbaru dari Molicel. 4500mAh dengan CDR 45A — high-power tertinggi di kelas 21700 saat ini.','specs'=>'Kapasitas: 4500mAh|Discharge: 45A CDR|Ukuran: 21700|Tegangan: 3.6V nominal|Isi: 2pcs','price'=>220000,'price_original'=>250000,'badge'=>'hot','color_gradient'=>'grad-blue','stock'=>20,'rating'=>4.9,'review_count'=>312],
        ];
    }
}
